### ISSUE TITLE
Asynchronously import axe-core

### ISSUE THREAD

**Issue by raunofreiberg** [raunofreiberg/axe-mode#9]
This is probably a pre-optimization, but I was thinking if we should maybe import `axe-core` asynchronously in the root component in an effect that would check for the `disabled` prop. 

This way `AxeMode` can always be wrapped around the application without including `axe-core` in the production bundle. I might be wrong though, but with a top-level synchronous import, it would be included regardless of it actually rendering.

I mean, it's possible to just manually remove the `AxeMode` component when building for production, but I think that would be annoying going back and forth with including/excluding it.

[The size of `axe-core`](https://bundlephobia.com/result?p=axe-core@3.5.3) is quite significant as well. Coming in at ~120kb minified and gzipped.

**Comment by chancestrickland** [comment]
Yeah, I considered this as well. Let's definitely consider this as we get close to a formal release.

**Comment by chancestrickland** [comment]
BTW, had some issues with the build and it looks like TSDX doesn't handle lazy loading at the moment. I updated the config but now we're not getting CJS bundles. This needs some work but we can probably open another PR for that.
